// Generated by GitHub Actions from the protected staging environment.
// The Supabase publishable/anon key is browser-safe and intentionally public.
export const stagingBrowserConfig = Object.freeze({
  "supabaseUrl": "https://jvxodxfheftylolhqoip.supabase.co",
  "supabaseAnonKey": "sb_publishable_p7vDTa2bN-1j95FnlvLQEg_mO9JzhXH",
  "appUrl": "https://acp-85qn.vercel.app",
  "environment": "staging"
} as const);
